version: '3.4'

services:
  mongodb:
    image: aashreys/mongo-auth:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin
      - MONGODB_APPLICATION_DATABASE=it-dojo-backend-api
      - MONGODB_APPLICATION_USER=it-dojo-backend-api
      - MONGODB_APPLICATION_PASS=it-dojo-backend-api

  nginx:
    image: nginx:1.13.10-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - it-dojo-backend-api

  it-dojo-backend-api:
    image: registry.it-dojo.io/it-dojo-backend-api:latest
    build: .
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bin/docker.static.18.03.0-ce:/usr/bin/docker
      - ./bin/tty-controller:/usr/bin/tty-controller
      - ./templates:/templates/
    working_dir: "/usr/src/app"
    command: python run.bjoern.py
    restart: on-failure:5
    env_file:
      - .env
    environment:
      - LANG=C.UTF-8
      - APP_ADMIN=admin@it-dojo.io
      - APP_FROM=no-reply@it-dojo.io
